# Generated by Django 5.0.7 on 2025-10-03 11:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Article title (5-200 characters)', max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of title (auto-generated if empty)', max_length=220, unique=True)),
                ('content', models.TextField(help_text='Article content (minimum 10 characters)', validators=[django.core.validators.MinLengthValidator(10)])),
                ('excerpt', models.CharField(blank=True, help_text='Brief description or excerpt (auto-generated from content if empty)', max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Article publication status', max_length=20)),
                ('featured', models.BooleanField(default=False, help_text='Mark as featured article')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times article has been viewed')),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags (e.g., 'python,django,api')", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when article was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when article was last updated')),
                ('published_at', models.DateTimeField(blank=True, help_text='Timestamp when article was published', null=True)),
                ('author', models.ForeignKey(help_text='Article author', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='articles_ar_status_cbb22b_idx'), models.Index(fields=['author', 'status'], name='articles_ar_author__8254d9_idx'), models.Index(fields=['featured'], name='articles_ar_feature_183843_idx')],
            },
        ),
    ]
